export class Permissions {
  static PUBLISH_CONTENT = "VIEW_STUDIO";
  static COMPANY_DETAILS = "COMPANY_DETAILS";
  static MANAGE_DASHBOARD = "MANAGE_DASHBOARD";
  static DELETE_ARCHIVED_CONTENT = "DELETE_ARCHIVED_CONTENT";
}