//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.07 at 12:17:09 PM IST 
//


package com.enablix.core.commons.xsdtopojo;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for contentTypeMappingConfigType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="contentTypeMappingConfigType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="contextConfig" type="{}contentTypeMappingContextType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "contentTypeMappingConfigType", propOrder = {
    "contextConfig"
})
public class ContentTypeMappingConfigType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected ContentTypeMappingContextType contextConfig;

    /**
     * Gets the value of the contextConfig property.
     * 
     * @return
     *     possible object is
     *     {@link ContentTypeMappingContextType }
     *     
     */
    public ContentTypeMappingContextType getContextConfig() {
        return contextConfig;
    }

    /**
     * Sets the value of the contextConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContentTypeMappingContextType }
     *     
     */
    public void setContextConfig(ContentTypeMappingContextType value) {
        this.contextConfig = value;
    }

}
