//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.07 at 12:17:09 PM IST 
//


package com.enablix.core.commons.xsdtopojo;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for focusItemMatchType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="focusItemMatchType">
 *   &lt;complexContent>
 *     &lt;extension base="{}conditionType">
 *       &lt;attribute name="itemQId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "focusItemMatchType")
public class FocusItemMatchType
    extends ConditionType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlAttribute(name = "itemQId")
    protected String itemQId;

    /**
     * Gets the value of the itemQId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemQId() {
        return itemQId;
    }

    /**
     * Sets the value of the itemQId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemQId(String value) {
        this.itemQId = value;
    }

}
