//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.09 at 03:09:46 PM IST 
//


package com.enablix.core.commons.xsdtopojo;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for groupConditionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="groupConditionType">
 *   &lt;complexContent>
 *     &lt;extension base="{}baseConditionType">
 *       &lt;sequence>
 *         &lt;element name="andCondition" type="{}andConditionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="orCondition" type="{}orConditionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="basicCondition" type="{}basicConditionType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "groupConditionType", propOrder = {
    "andCondition",
    "orCondition",
    "basicCondition"
})
@XmlSeeAlso({
    OrConditionType.class,
    AndConditionType.class
})
public class GroupConditionType
    extends BaseConditionType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected List<AndConditionType> andCondition;
    protected List<OrConditionType> orCondition;
    protected List<BasicConditionType> basicCondition;

    /**
     * Gets the value of the andCondition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the andCondition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAndCondition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AndConditionType }
     * 
     * 
     */
    public List<AndConditionType> getAndCondition() {
        if (andCondition == null) {
            andCondition = new ArrayList<AndConditionType>();
        }
        return this.andCondition;
    }

    /**
     * Gets the value of the orCondition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the orCondition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrCondition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrConditionType }
     * 
     * 
     */
    public List<OrConditionType> getOrCondition() {
        if (orCondition == null) {
            orCondition = new ArrayList<OrConditionType>();
        }
        return this.orCondition;
    }

    /**
     * Gets the value of the basicCondition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the basicCondition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBasicCondition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BasicConditionType }
     * 
     * 
     */
    public List<BasicConditionType> getBasicCondition() {
        if (basicCondition == null) {
            basicCondition = new ArrayList<BasicConditionType>();
        }
        return this.basicCondition;
    }

}
