//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.07 at 12:17:09 PM IST 
//


package com.enablix.core.commons.xsdtopojo;

import java.io.Serializable;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for laterExecutionTimeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="laterExecutionTimeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="resetOn" type="{}resetExecutionOnType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="timeUnit" type="{}timeUnitEnum" />
 *       &lt;attribute name="timeValue" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "laterExecutionTimeType", propOrder = {
    "resetOn"
})
public class LaterExecutionTimeType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected ResetExecutionOnType resetOn;
    @XmlAttribute(name = "timeUnit")
    protected TimeUnitEnum timeUnit;
    @XmlAttribute(name = "timeValue")
    protected BigInteger timeValue;

    /**
     * Gets the value of the resetOn property.
     * 
     * @return
     *     possible object is
     *     {@link ResetExecutionOnType }
     *     
     */
    public ResetExecutionOnType getResetOn() {
        return resetOn;
    }

    /**
     * Sets the value of the resetOn property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResetExecutionOnType }
     *     
     */
    public void setResetOn(ResetExecutionOnType value) {
        this.resetOn = value;
    }

    /**
     * Gets the value of the timeUnit property.
     * 
     * @return
     *     possible object is
     *     {@link TimeUnitEnum }
     *     
     */
    public TimeUnitEnum getTimeUnit() {
        return timeUnit;
    }

    /**
     * Sets the value of the timeUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeUnitEnum }
     *     
     */
    public void setTimeUnit(TimeUnitEnum value) {
        this.timeUnit = value;
    }

    /**
     * Gets the value of the timeValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTimeValue() {
        return timeValue;
    }

    /**
     * Sets the value of the timeValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTimeValue(BigInteger value) {
        this.timeValue = value;
    }

}
