//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.02 at 04:35:33 PM IST 
//


package com.enablix.core.commons.xsdtopojo;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.enablix.core.commons.xsdtopojo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.enablix.core.commons.xsdtopojo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CorrelationActionType }
     * 
     */
    public CorrelationActionType createCorrelationActionType() {
        return new CorrelationActionType();
    }

    /**
     * Create an instance of {@link TextUIDefType }
     * 
     */
    public TextUIDefType createTextUIDefType() {
        return new TextUIDefType();
    }

    /**
     * Create an instance of {@link BoundedUIDefType }
     * 
     */
    public BoundedUIDefType createBoundedUIDefType() {
        return new BoundedUIDefType();
    }

    /**
     * Create an instance of {@link EmailTemplateType }
     * 
     */
    public EmailTemplateType createEmailTemplateType() {
        return new EmailTemplateType();
    }

    /**
     * Create an instance of {@link ShowContentItemType }
     * 
     */
    public ShowContentItemType createShowContentItemType() {
        return new ShowContentItemType();
    }

    /**
     * Create an instance of {@link ContainerPortalConfigType.HeadingContentItem }
     * 
     */
    public ContainerPortalConfigType.HeadingContentItem createContainerPortalConfigTypeHeadingContentItem() {
        return new ContainerPortalConfigType.HeadingContentItem();
    }

    /**
     * Create an instance of {@link BaseEmailContentType }
     * 
     */
    public BaseEmailContentType createBaseEmailContentType() {
        return new BaseEmailContentType();
    }

    /**
     * Create an instance of {@link ContainerMappingsType }
     * 
     */
    public ContainerMappingsType createContainerMappingsType() {
        return new ContainerMappingsType();
    }

    /**
     * Create an instance of {@link UiDefinitionType }
     * 
     */
    public UiDefinitionType createUiDefinitionType() {
        return new UiDefinitionType();
    }

    /**
     * Create an instance of {@link PlayExecutionType }
     * 
     */
    public PlayExecutionType createPlayExecutionType() {
        return new PlayExecutionType();
    }

    /**
     * Create an instance of {@link FilteredUserSetType }
     * 
     */
    public FilteredUserSetType createFilteredUserSetType() {
        return new FilteredUserSetType();
    }

    /**
     * Create an instance of {@link SourceIdType }
     * 
     */
    public SourceIdType createSourceIdType() {
        return new SourceIdType();
    }

    /**
     * Create an instance of {@link OrConditionType }
     * 
     */
    public OrConditionType createOrConditionType() {
        return new OrConditionType();
    }

    /**
     * Create an instance of {@link DocUIDefType }
     * 
     */
    public DocUIDefType createDocUIDefType() {
        return new DocUIDefType();
    }

    /**
     * Create an instance of {@link AutoSuggestType }
     * 
     */
    public AutoSuggestType createAutoSuggestType() {
        return new AutoSuggestType();
    }

    /**
     * Create an instance of {@link BaseConditionType }
     * 
     */
    public BaseConditionType createBaseConditionType() {
        return new BaseConditionType();
    }

    /**
     * Create an instance of {@link ContainerListViewConfigType.HideContentItem }
     * 
     */
    public ContainerListViewConfigType.HideContentItem createContainerListViewConfigTypeHideContentItem() {
        return new ContainerListViewConfigType.HideContentItem();
    }

    /**
     * Create an instance of {@link PortalTopNavEnclosuresType }
     * 
     */
    public PortalTopNavEnclosuresType createPortalTopNavEnclosuresType() {
        return new PortalTopNavEnclosuresType();
    }

    /**
     * Create an instance of {@link ReevaluatePendingCheckpointType }
     * 
     */
    public ReevaluatePendingCheckpointType createReevaluatePendingCheckpointType() {
        return new ReevaluatePendingCheckpointType();
    }

    /**
     * Create an instance of {@link BoundedFixedListType }
     * 
     */
    public BoundedFixedListType createBoundedFixedListType() {
        return new BoundedFixedListType();
    }

    /**
     * Create an instance of {@link UserGroupRefType }
     * 
     */
    public UserGroupRefType createUserGroupRefType() {
        return new UserGroupRefType();
    }

    /**
     * Create an instance of {@link PortalContentCondensedViewType }
     * 
     */
    public PortalContentCondensedViewType createPortalContentCondensedViewType() {
        return new PortalContentCondensedViewType();
    }

    /**
     * Create an instance of {@link ContainerType }
     * 
     */
    public ContainerType createContainerType() {
        return new ContainerType();
    }

    /**
     * Create an instance of {@link ExecutionTimeType }
     * 
     */
    public ExecutionTimeType createExecutionTimeType() {
        return new ExecutionTimeType();
    }

    /**
     * Create an instance of {@link ReferenceUserSetType }
     * 
     */
    public ReferenceUserSetType createReferenceUserSetType() {
        return new ReferenceUserSetType();
    }

    /**
     * Create an instance of {@link ConditionType }
     * 
     */
    public ConditionType createConditionType() {
        return new ConditionType();
    }

    /**
     * Create an instance of {@link EmailContentTriggerEntityType }
     * 
     */
    public EmailContentTriggerEntityType createEmailContentTriggerEntityType() {
        return new EmailContentTriggerEntityType();
    }

    /**
     * Create an instance of {@link BaseContentType }
     * 
     */
    public BaseContentType createBaseContentType() {
        return new BaseContentType();
    }

    /**
     * Create an instance of {@link ContainerListViewConfigType }
     * 
     */
    public ContainerListViewConfigType createContainerListViewConfigType() {
        return new ContainerListViewConfigType();
    }

    /**
     * Create an instance of {@link RelatedItemType }
     * 
     */
    public RelatedItemType createRelatedItemType() {
        return new RelatedItemType();
    }

    /**
     * Create an instance of {@link UserGroupsType }
     * 
     */
    public UserGroupsType createUserGroupsType() {
        return new UserGroupsType();
    }

    /**
     * Create an instance of {@link RelatedUserType }
     * 
     */
    public RelatedUserType createRelatedUserType() {
        return new RelatedUserType();
    }

    /**
     * Create an instance of {@link PortalUIDefType }
     * 
     */
    public PortalUIDefType createPortalUIDefType() {
        return new PortalUIDefType();
    }

    /**
     * Create an instance of {@link FocusItemRefType }
     * 
     */
    public FocusItemRefType createFocusItemRefType() {
        return new FocusItemRefType();
    }

    /**
     * Create an instance of {@link ContentRecordType }
     * 
     */
    public ContentRecordType createContentRecordType() {
        return new ContentRecordType();
    }

    /**
     * Create an instance of {@link EmailAllUsersType }
     * 
     */
    public EmailAllUsersType createEmailAllUsersType() {
        return new EmailAllUsersType();
    }

    /**
     * Create an instance of {@link ContainerDataContextType }
     * 
     */
    public ContainerDataContextType createContainerDataContextType() {
        return new ContainerDataContextType();
    }

    /**
     * Create an instance of {@link IdentifiableType }
     * 
     */
    public IdentifiableType createIdentifiableType() {
        return new IdentifiableType();
    }

    /**
     * Create an instance of {@link ContentGroupType }
     * 
     */
    public ContentGroupType createContentGroupType() {
        return new ContentGroupType();
    }

    /**
     * Create an instance of {@link EmailContentType }
     * 
     */
    public EmailContentType createEmailContentType() {
        return new EmailContentType();
    }

    /**
     * Create an instance of {@link FocusItemAttrType }
     * 
     */
    public FocusItemAttrType createFocusItemAttrType() {
        return new FocusItemAttrType();
    }

    /**
     * Create an instance of {@link EntityContentType }
     * 
     */
    public EntityContentType createEntityContentType() {
        return new EntityContentType();
    }

    /**
     * Create an instance of {@link DateTimeType }
     * 
     */
    public DateTimeType createDateTimeType() {
        return new DateTimeType();
    }

    /**
     * Create an instance of {@link CondValueType }
     * 
     */
    public CondValueType createCondValueType() {
        return new CondValueType();
    }

    /**
     * Create an instance of {@link AttributeCheckType }
     * 
     */
    public AttributeCheckType createAttributeCheckType() {
        return new AttributeCheckType();
    }

    /**
     * Create an instance of {@link ContentContainerMappingType }
     * 
     */
    public ContentContainerMappingType createContentContainerMappingType() {
        return new ContentContainerMappingType();
    }

    /**
     * Create an instance of {@link AndConditionType }
     * 
     */
    public AndConditionType createAndConditionType() {
        return new AndConditionType();
    }

    /**
     * Create an instance of {@link LifecycleType }
     * 
     */
    public LifecycleType createLifecycleType() {
        return new LifecycleType();
    }

    /**
     * Create an instance of {@link RichTextType }
     * 
     */
    public RichTextType createRichTextType() {
        return new RichTextType();
    }

    /**
     * Create an instance of {@link FixedListDataType }
     * 
     */
    public FixedListDataType createFixedListDataType() {
        return new FixedListDataType();
    }

    /**
     * Create an instance of {@link DiskDocType }
     * 
     */
    public DiskDocType createDiskDocType() {
        return new DiskDocType();
    }

    /**
     * Create an instance of {@link EmailContentGroupsType }
     * 
     */
    public EmailContentGroupsType createEmailContentGroupsType() {
        return new EmailContentGroupsType();
    }

    /**
     * Create an instance of {@link MatchType }
     * 
     */
    public MatchType createMatchType() {
        return new MatchType();
    }

    /**
     * Create an instance of {@link RecurringScheduleType }
     * 
     */
    public RecurringScheduleType createRecurringScheduleType() {
        return new RecurringScheduleType();
    }

    /**
     * Create an instance of {@link ContentStackType }
     * 
     */
    public ContentStackType createContentStackType() {
        return new ContentStackType();
    }

    /**
     * Create an instance of {@link ActionType }
     * 
     */
    public ActionType createActionType() {
        return new ActionType();
    }

    /**
     * Create an instance of {@link ChildEnclosureType.ChildContainer }
     * 
     */
    public ChildEnclosureType.ChildContainer createChildEnclosureTypeChildContainer() {
        return new ChildEnclosureType.ChildContainer();
    }

    /**
     * Create an instance of {@link TriggerEntityUpdateCondType }
     * 
     */
    public TriggerEntityUpdateCondType createTriggerEntityUpdateCondType() {
        return new TriggerEntityUpdateCondType();
    }

    /**
     * Create an instance of {@link CheckboxType }
     * 
     */
    public CheckboxType createCheckboxType() {
        return new CheckboxType();
    }

    /**
     * Create an instance of {@link EmailCorrelatedUsersType }
     * 
     */
    public EmailCorrelatedUsersType createEmailCorrelatedUsersType() {
        return new EmailCorrelatedUsersType();
    }

    /**
     * Create an instance of {@link ContentGroupRefType }
     * 
     */
    public ContentGroupRefType createContentGroupRefType() {
        return new ContentGroupRefType();
    }

    /**
     * Create an instance of {@link BaseEmailRecipientType }
     * 
     */
    public BaseEmailRecipientType createBaseEmailRecipientType() {
        return new BaseEmailRecipientType();
    }

    /**
     * Create an instance of {@link ItemUserCorrelationRules }
     * 
     */
    public ItemUserCorrelationRules createItemUserCorrelationRules() {
        return new ItemUserCorrelationRules();
    }

    /**
     * Create an instance of {@link TopNavType }
     * 
     */
    public TopNavType createTopNavType() {
        return new TopNavType();
    }

    /**
     * Create an instance of {@link FilterType }
     * 
     */
    public FilterType createFilterType() {
        return new FilterType();
    }

    /**
     * Create an instance of {@link ChildEnclosureType }
     * 
     */
    public ChildEnclosureType createChildEnclosureType() {
        return new ChildEnclosureType();
    }

    /**
     * Create an instance of {@link ContentCorrelatedItemType }
     * 
     */
    public ContentCorrelatedItemType createContentCorrelatedItemType() {
        return new ContentCorrelatedItemType();
    }

    /**
     * Create an instance of {@link PlayTemplate }
     * 
     */
    public PlayTemplate createPlayTemplate() {
        return new PlayTemplate();
    }

    /**
     * Create an instance of {@link CheckpointType }
     * 
     */
    public CheckpointType createCheckpointType() {
        return new CheckpointType();
    }

    /**
     * Create an instance of {@link FocusItemType }
     * 
     */
    public FocusItemType createFocusItemType() {
        return new FocusItemType();
    }

    /**
     * Create an instance of {@link FilterConstantType }
     * 
     */
    public FilterConstantType createFilterConstantType() {
        return new FilterConstantType();
    }

    /**
     * Create an instance of {@link MatchCriteriaType }
     * 
     */
    public MatchCriteriaType createMatchCriteriaType() {
        return new MatchCriteriaType();
    }

    /**
     * Create an instance of {@link RelatedUsersType }
     * 
     */
    public RelatedUsersType createRelatedUsersType() {
        return new RelatedUsersType();
    }

    /**
     * Create an instance of {@link ContentMapping }
     * 
     */
    public ContentMapping createContentMapping() {
        return new ContentMapping();
    }

    /**
     * Create an instance of {@link DateTimeUIDefType }
     * 
     */
    public DateTimeUIDefType createDateTimeUIDefType() {
        return new DateTimeUIDefType();
    }

    /**
     * Create an instance of {@link ContentTypeMappingContextType }
     * 
     */
    public ContentTypeMappingContextType createContentTypeMappingContextType() {
        return new ContentTypeMappingContextType();
    }

    /**
     * Create an instance of {@link UserSetType }
     * 
     */
    public UserSetType createUserSetType() {
        return new UserSetType();
    }

    /**
     * Create an instance of {@link RadioButtonType }
     * 
     */
    public RadioButtonType createRadioButtonType() {
        return new RadioButtonType();
    }

    /**
     * Create an instance of {@link FilterCriteriaType }
     * 
     */
    public FilterCriteriaType createFilterCriteriaType() {
        return new FilterCriteriaType();
    }

    /**
     * Create an instance of {@link EmailUsersType }
     * 
     */
    public EmailUsersType createEmailUsersType() {
        return new EmailUsersType();
    }

    /**
     * Create an instance of {@link FocusItemMatchType }
     * 
     */
    public FocusItemMatchType createFocusItemMatchType() {
        return new FocusItemMatchType();
    }

    /**
     * Create an instance of {@link ContentTemplate }
     * 
     */
    public ContentTemplate createContentTemplate() {
        return new ContentTemplate();
    }

    /**
     * Create an instance of {@link ItemUserCorrelationRuleType }
     * 
     */
    public ItemUserCorrelationRuleType createItemUserCorrelationRuleType() {
        return new ItemUserCorrelationRuleType();
    }

    /**
     * Create an instance of {@link NumericType }
     * 
     */
    public NumericType createNumericType() {
        return new NumericType();
    }

    /**
     * Create an instance of {@link PathItemType }
     * 
     */
    public PathItemType createPathItemType() {
        return new PathItemType();
    }

    /**
     * Create an instance of {@link ItemCorrelationRules }
     * 
     */
    public ItemCorrelationRules createItemCorrelationRules() {
        return new ItemCorrelationRules();
    }

    /**
     * Create an instance of {@link ContentGroupsType }
     * 
     */
    public ContentGroupsType createContentGroupsType() {
        return new ContentGroupsType();
    }

    /**
     * Create an instance of {@link ContentItemType }
     * 
     */
    public ContentItemType createContentItemType() {
        return new ContentItemType();
    }

    /**
     * Create an instance of {@link UpdateOnExecType }
     * 
     */
    public UpdateOnExecType createUpdateOnExecType() {
        return new UpdateOnExecType();
    }

    /**
     * Create an instance of {@link FilterTagsType }
     * 
     */
    public FilterTagsType createFilterTagsType() {
        return new FilterTagsType();
    }

    /**
     * Create an instance of {@link ContentItemMappingsType }
     * 
     */
    public ContentItemMappingsType createContentItemMappingsType() {
        return new ContentItemMappingsType();
    }

    /**
     * Create an instance of {@link ActionsType }
     * 
     */
    public ActionsType createActionsType() {
        return new ActionsType();
    }

    /**
     * Create an instance of {@link BoundedRefListType }
     * 
     */
    public BoundedRefListType createBoundedRefListType() {
        return new BoundedRefListType();
    }

    /**
     * Create an instance of {@link ItemContainersType }
     * 
     */
    public ItemContainersType createItemContainersType() {
        return new ItemContainersType();
    }

    /**
     * Create an instance of {@link DocType }
     * 
     */
    public DocType createDocType() {
        return new DocType();
    }

    /**
     * Create an instance of {@link ItemCorrelationRuleType }
     * 
     */
    public ItemCorrelationRuleType createItemCorrelationRuleType() {
        return new ItemCorrelationRuleType();
    }

    /**
     * Create an instance of {@link UserProfileRefType }
     * 
     */
    public UserProfileRefType createUserProfileRefType() {
        return new UserProfileRefType();
    }

    /**
     * Create an instance of {@link DisableExecutionOnType }
     * 
     */
    public DisableExecutionOnType createDisableExecutionOnType() {
        return new DisableExecutionOnType();
    }

    /**
     * Create an instance of {@link ResetExecutionOnType }
     * 
     */
    public ResetExecutionOnType createResetExecutionOnType() {
        return new ResetExecutionOnType();
    }

    /**
     * Create an instance of {@link GroupConditionType }
     * 
     */
    public GroupConditionType createGroupConditionType() {
        return new GroupConditionType();
    }

    /**
     * Create an instance of {@link PlayScopeType }
     * 
     */
    public PlayScopeType createPlayScopeType() {
        return new PlayScopeType();
    }

    /**
     * Create an instance of {@link ContainerUIDefType }
     * 
     */
    public ContainerUIDefType createContainerUIDefType() {
        return new ContainerUIDefType();
    }

    /**
     * Create an instance of {@link ContainerMappingType }
     * 
     */
    public ContainerMappingType createContainerMappingType() {
        return new ContainerMappingType();
    }

    /**
     * Create an instance of {@link EmailUserGroupsType }
     * 
     */
    public EmailUserGroupsType createEmailUserGroupsType() {
        return new EmailUserGroupsType();
    }

    /**
     * Create an instance of {@link TriggerItemType }
     * 
     */
    public TriggerItemType createTriggerItemType() {
        return new TriggerItemType();
    }

    /**
     * Create an instance of {@link ContentItemMappingType }
     * 
     */
    public ContentItemMappingType createContentItemMappingType() {
        return new ContentItemMappingType();
    }

    /**
     * Create an instance of {@link BasicConditionType }
     * 
     */
    public BasicConditionType createBasicConditionType() {
        return new BasicConditionType();
    }

    /**
     * Create an instance of {@link FilterParentAttributeType }
     * 
     */
    public FilterParentAttributeType createFilterParentAttributeType() {
        return new FilterParentAttributeType();
    }

    /**
     * Create an instance of {@link DataDefinitionType }
     * 
     */
    public DataDefinitionType createDataDefinitionType() {
        return new DataDefinitionType();
    }

    /**
     * Create an instance of {@link TextType }
     * 
     */
    public TextType createTextType() {
        return new TextType();
    }

    /**
     * Create an instance of {@link TemplateType }
     * 
     */
    public TemplateType createTemplateType() {
        return new TemplateType();
    }

    /**
     * Create an instance of {@link ContentSetType }
     * 
     */
    public ContentSetType createContentSetType() {
        return new ContentSetType();
    }

    /**
     * Create an instance of {@link ContainerPortalConfigType }
     * 
     */
    public ContainerPortalConfigType createContainerPortalConfigType() {
        return new ContainerPortalConfigType();
    }

    /**
     * Create an instance of {@link TimeReferenceType }
     * 
     */
    public TimeReferenceType createTimeReferenceType() {
        return new TimeReferenceType();
    }

    /**
     * Create an instance of {@link ExecConditionType }
     * 
     */
    public ExecConditionType createExecConditionType() {
        return new ExecConditionType();
    }

    /**
     * Create an instance of {@link BoundedListDatastoreType }
     * 
     */
    public BoundedListDatastoreType createBoundedListDatastoreType() {
        return new BoundedListDatastoreType();
    }

    /**
     * Create an instance of {@link RelatedUserPathType }
     * 
     */
    public RelatedUserPathType createRelatedUserPathType() {
        return new RelatedUserPathType();
    }

    /**
     * Create an instance of {@link DropdownType }
     * 
     */
    public DropdownType createDropdownType() {
        return new DropdownType();
    }

    /**
     * Create an instance of {@link NumericUIDefType }
     * 
     */
    public NumericUIDefType createNumericUIDefType() {
        return new NumericUIDefType();
    }

    /**
     * Create an instance of {@link CandidateContainersType }
     * 
     */
    public CandidateContainersType createCandidateContainersType() {
        return new CandidateContainersType();
    }

    /**
     * Create an instance of {@link FocusItemsType }
     * 
     */
    public FocusItemsType createFocusItemsType() {
        return new FocusItemsType();
    }

    /**
     * Create an instance of {@link LaterExecutionTimeType }
     * 
     */
    public LaterExecutionTimeType createLaterExecutionTimeType() {
        return new LaterExecutionTimeType();
    }

    /**
     * Create an instance of {@link DescribedType }
     * 
     */
    public DescribedType createDescribedType() {
        return new DescribedType();
    }

    /**
     * Create an instance of {@link ContentTriggerDefType }
     * 
     */
    public ContentTriggerDefType createContentTriggerDefType() {
        return new ContentTriggerDefType();
    }

    /**
     * Create an instance of {@link CondAttrType }
     * 
     */
    public CondAttrType createCondAttrType() {
        return new CondAttrType();
    }

    /**
     * Create an instance of {@link ItemContainerType }
     * 
     */
    public ItemContainerType createItemContainerType() {
        return new ItemContainerType();
    }

    /**
     * Create an instance of {@link RelatedItemsType }
     * 
     */
    public RelatedItemsType createRelatedItemsType() {
        return new RelatedItemsType();
    }

    /**
     * Create an instance of {@link CorrelatedEntitiesType }
     * 
     */
    public CorrelatedEntitiesType createCorrelatedEntitiesType() {
        return new CorrelatedEntitiesType();
    }

    /**
     * Create an instance of {@link TriggersDef }
     * 
     */
    public TriggersDef createTriggersDef() {
        return new TriggersDef();
    }

    /**
     * Create an instance of {@link AttributeUpdateType }
     * 
     */
    public AttributeUpdateType createAttributeUpdateType() {
        return new AttributeUpdateType();
    }

    /**
     * Create an instance of {@link BoundedType }
     * 
     */
    public BoundedType createBoundedType() {
        return new BoundedType();
    }

    /**
     * Create an instance of {@link SytemUserMappingType }
     * 
     */
    public SytemUserMappingType createSytemUserMappingType() {
        return new SytemUserMappingType();
    }

    /**
     * Create an instance of {@link EmailActionType }
     * 
     */
    public EmailActionType createEmailActionType() {
        return new EmailActionType();
    }

    /**
     * Create an instance of {@link BaseContainerType }
     * 
     */
    public BaseContainerType createBaseContainerType() {
        return new BaseContainerType();
    }

    /**
     * Create an instance of {@link TagsType }
     * 
     */
    public TagsType createTagsType() {
        return new TagsType();
    }

    /**
     * Create an instance of {@link DescribedAndVersionedType }
     * 
     */
    public DescribedAndVersionedType createDescribedAndVersionedType() {
        return new DescribedAndVersionedType();
    }

    /**
     * Create an instance of {@link FocusItemCorrelatedContentType }
     * 
     */
    public FocusItemCorrelatedContentType createFocusItemCorrelatedContentType() {
        return new FocusItemCorrelatedContentType();
    }

    /**
     * Create an instance of {@link FocusItemRecordType }
     * 
     */
    public FocusItemRecordType createFocusItemRecordType() {
        return new FocusItemRecordType();
    }

    /**
     * Create an instance of {@link EmailRecipientType }
     * 
     */
    public EmailRecipientType createEmailRecipientType() {
        return new EmailRecipientType();
    }

    /**
     * Create an instance of {@link ContentUIDefType }
     * 
     */
    public ContentUIDefType createContentUIDefType() {
        return new ContentUIDefType();
    }

    /**
     * Create an instance of {@link ParentContainerMappingType }
     * 
     */
    public ParentContainerMappingType createParentContainerMappingType() {
        return new ParentContainerMappingType();
    }

    /**
     * Create an instance of {@link UpdateOnContentGroupsType }
     * 
     */
    public UpdateOnContentGroupsType createUpdateOnContentGroupsType() {
        return new UpdateOnContentGroupsType();
    }

    /**
     * Create an instance of {@link ContentTypeMappingConfigType }
     * 
     */
    public ContentTypeMappingConfigType createContentTypeMappingConfigType() {
        return new ContentTypeMappingConfigType();
    }

    /**
     * Create an instance of {@link UserGroupType }
     * 
     */
    public UserGroupType createUserGroupType() {
        return new UserGroupType();
    }

}
