//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.18 at 06:49:09 PM IST 
//


package com.enablix.core.commons.xsdtopojo;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.enablix.core.commons.xsdtopojo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.enablix.core.commons.xsdtopojo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BoundedFixedListType }
     * 
     */
    public BoundedFixedListType createBoundedFixedListType() {
        return new BoundedFixedListType();
    }

    /**
     * Create an instance of {@link RadioButtonType }
     * 
     */
    public RadioButtonType createRadioButtonType() {
        return new RadioButtonType();
    }

    /**
     * Create an instance of {@link TextType }
     * 
     */
    public TextType createTextType() {
        return new TextType();
    }

    /**
     * Create an instance of {@link DiskDocType }
     * 
     */
    public DiskDocType createDiskDocType() {
        return new DiskDocType();
    }

    /**
     * Create an instance of {@link BoundedRefListType }
     * 
     */
    public BoundedRefListType createBoundedRefListType() {
        return new BoundedRefListType();
    }

    /**
     * Create an instance of {@link UiDefinitionType }
     * 
     */
    public UiDefinitionType createUiDefinitionType() {
        return new UiDefinitionType();
    }

    /**
     * Create an instance of {@link ContentItemType }
     * 
     */
    public ContentItemType createContentItemType() {
        return new ContentItemType();
    }

    /**
     * Create an instance of {@link BoundedUIDefType }
     * 
     */
    public BoundedUIDefType createBoundedUIDefType() {
        return new BoundedUIDefType();
    }

    /**
     * Create an instance of {@link DocType }
     * 
     */
    public DocType createDocType() {
        return new DocType();
    }

    /**
     * Create an instance of {@link TextUIDefType }
     * 
     */
    public TextUIDefType createTextUIDefType() {
        return new TextUIDefType();
    }

    /**
     * Create an instance of {@link ContainerUIDefType }
     * 
     */
    public ContainerUIDefType createContainerUIDefType() {
        return new ContainerUIDefType();
    }

    /**
     * Create an instance of {@link DateTimeType }
     * 
     */
    public DateTimeType createDateTimeType() {
        return new DateTimeType();
    }

    /**
     * Create an instance of {@link BoundedType }
     * 
     */
    public BoundedType createBoundedType() {
        return new BoundedType();
    }

    /**
     * Create an instance of {@link NumericUIDefType }
     * 
     */
    public NumericUIDefType createNumericUIDefType() {
        return new NumericUIDefType();
    }

    /**
     * Create an instance of {@link ContentUIDefType }
     * 
     */
    public ContentUIDefType createContentUIDefType() {
        return new ContentUIDefType();
    }

    /**
     * Create an instance of {@link AutoSuggestType }
     * 
     */
    public AutoSuggestType createAutoSuggestType() {
        return new AutoSuggestType();
    }

    /**
     * Create an instance of {@link ContentTemplate }
     * 
     */
    public ContentTemplate createContentTemplate() {
        return new ContentTemplate();
    }

    /**
     * Create an instance of {@link DataDefinitionType }
     * 
     */
    public DataDefinitionType createDataDefinitionType() {
        return new DataDefinitionType();
    }

    /**
     * Create an instance of {@link DocUIDefType }
     * 
     */
    public DocUIDefType createDocUIDefType() {
        return new DocUIDefType();
    }

    /**
     * Create an instance of {@link DropdownType }
     * 
     */
    public DropdownType createDropdownType() {
        return new DropdownType();
    }

    /**
     * Create an instance of {@link NumericType }
     * 
     */
    public NumericType createNumericType() {
        return new NumericType();
    }

    /**
     * Create an instance of {@link BoundedListDatastoreType }
     * 
     */
    public BoundedListDatastoreType createBoundedListDatastoreType() {
        return new BoundedListDatastoreType();
    }

    /**
     * Create an instance of {@link FixedListDataType }
     * 
     */
    public FixedListDataType createFixedListDataType() {
        return new FixedListDataType();
    }

    /**
     * Create an instance of {@link BaseContentType }
     * 
     */
    public BaseContentType createBaseContentType() {
        return new BaseContentType();
    }

    /**
     * Create an instance of {@link DateTimeUIDefType }
     * 
     */
    public DateTimeUIDefType createDateTimeUIDefType() {
        return new DateTimeUIDefType();
    }

    /**
     * Create an instance of {@link ContainerType }
     * 
     */
    public ContainerType createContainerType() {
        return new ContainerType();
    }

    /**
     * Create an instance of {@link CheckboxType }
     * 
     */
    public CheckboxType createCheckboxType() {
        return new CheckboxType();
    }

    /**
     * Create an instance of {@link BaseContainerType }
     * 
     */
    public BaseContainerType createBaseContainerType() {
        return new BaseContainerType();
    }

}
