//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.15 at 04:59:14 PM IST 
//


package com.enablix.core.commons.xsdtopojo;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for qualityControlledContentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="qualityControlledContentType">
 *   &lt;complexContent>
 *     &lt;extension base="{}baseContentType">
 *       &lt;sequence>
 *         &lt;element name="qualityConfig" type="{}qualityConfigType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "qualityControlledContentType", propOrder = {
    "qualityConfig"
})
@XmlSeeAlso({
    ContentItemType.class,
    BaseContainerType.class
})
public class QualityControlledContentType
    extends BaseContentType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected QualityConfigType qualityConfig;

    /**
     * Gets the value of the qualityConfig property.
     * 
     * @return
     *     possible object is
     *     {@link QualityConfigType }
     *     
     */
    public QualityConfigType getQualityConfig() {
        return qualityConfig;
    }

    /**
     * Sets the value of the qualityConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link QualityConfigType }
     *     
     */
    public void setQualityConfig(QualityConfigType value) {
        this.qualityConfig = value;
    }

}
