//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.10 at 03:12:36 PM IST 
//


package com.enablix.core.commons.xsdtopojo;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for qualityConfigType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="qualityConfigType">
 *   &lt;complexContent>
 *     &lt;extension base="{}paramSetType">
 *       &lt;sequence>
 *         &lt;element name="paramSet" type="{}paramSetType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "qualityConfigType", propOrder = {
    "paramSet"
})
public class QualityConfigType
    extends ParamSetType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected List<ParamSetType> paramSet;

    /**
     * Gets the value of the paramSet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the paramSet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParamSet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ParamSetType }
     * 
     * 
     */
    public List<ParamSetType> getParamSet() {
        if (paramSet == null) {
            paramSet = new ArrayList<ParamSetType>();
        }
        return this.paramSet;
    }

}
