//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.05 at 06:09:53 PM IST 
//


package com.enablix.core.commons.xsdtopojo;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for referenceUserSetType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="referenceUserSetType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="focusItemAttr" type="{}focusItemAttrType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "referenceUserSetType", propOrder = {
    "focusItemAttr"
})
public class ReferenceUserSetType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected FocusItemAttrType focusItemAttr;

    /**
     * Gets the value of the focusItemAttr property.
     * 
     * @return
     *     possible object is
     *     {@link FocusItemAttrType }
     *     
     */
    public FocusItemAttrType getFocusItemAttr() {
        return focusItemAttr;
    }

    /**
     * Sets the value of the focusItemAttr property.
     * 
     * @param value
     *     allowed object is
     *     {@link FocusItemAttrType }
     *     
     */
    public void setFocusItemAttr(FocusItemAttrType value) {
        this.focusItemAttr = value;
    }

}
